import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { CyberIncidentDTO } from '@/shared/api/dto-adapters/cyber';
import { EmptyState, ErrorState, LoadingSkeleton, SeverityBadge } from '@/shared/components';
import { Badge, Button } from '@/shared/ui-kit';

type SortKey='id'|'type'|'severity'|'date'|'status'|'target';
export function CyberIncidentTable({ incidents, loading=false, error, onRetry }: { incidents:CyberIncidentDTO[]; loading?:boolean; error?:Error|null; onRetry?:()=>void }){
 const navigate=useNavigate(); const [sort,setSort]=useState<SortKey>('date'); const [desc,setDesc]=useState(true); const [page,setPage]=useState(1); const pageSize=20;
 const sorted=useMemo(()=>[...incidents].sort((a,b)=>{const r=String(a[sort]).localeCompare(String(b[sort])); return desc?-r:r;}),[incidents,sort,desc]); const pages=Math.max(1,Math.ceil(sorted.length/pageSize)); const visible=sorted.slice((page-1)*pageSize,page*pageSize);
 if(loading) return <div className="grid gap-2">{Array.from({length:10}).map((_,i)=><LoadingSkeleton key={i} variant="table-row" />)}</div>; if(error) return <ErrorState message={error.message} onRetry={onRetry}/>; if(!incidents.length) return <EmptyState title="No cyber incidents" description="No incidents match your current filters."/>;
 const heads: Array<{key:SortKey;label:string}>=[{key:'id',label:'ID'},{key:'type',label:'Type'},{key:'severity',label:'Severity'},{key:'date',label:'Date'},{key:'status',label:'Status'},{key:'target',label:'Target'}];
 return <div className="glass-card overflow-hidden rounded-[var(--radius-2xl)]"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/5 text-xs uppercase tracking-[0.16em] text-[var(--color-text-muted)]"><tr>{heads.map(h=><th key={h.key} className="px-4 py-3"><button onClick={()=>{setSort(h.key);setDesc(sort===h.key?!desc:false)}}>{h.label}</button></th>)}<th className="px-4 py-3">Actions</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} onClick={()=>navigate(`/cyber/cases/${encodeURIComponent(row.id)}`)} className="cursor-pointer border-t border-[var(--color-border)] hover:bg-white/5"><td className="px-4 py-3 font-mono text-xs text-[var(--color-cyber-cyan)]">{row.id}</td><td className="px-4 py-3 font-semibold">{row.type}</td><td className="px-4 py-3"><SeverityBadge severity={row.severity as 'extreme'|'high'|'medium'|'low'} /></td><td className="px-4 py-3">{row.date}</td><td className="px-4 py-3"><Badge variant={row.status==='Resolved'?'green':row.status==='Open'?'red':'amber'}>{row.status}</Badge></td><td className="px-4 py-3">{row.target}</td><td className="px-4 py-3"><Button size="sm" variant="ghost">View</Button></td></tr>)}</tbody></table></div><div className="flex justify-between p-3 text-sm text-[var(--color-text-secondary)]"><span>Showing {(page-1)*pageSize+1}-{Math.min(page*pageSize,sorted.length)} of {sorted.length}</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Prev</Button><span>Page {page}/{pages}</span><Button size="sm" variant="secondary" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></div>;
}
