export interface CyberIncidentDTO { id:string; type:string; severity:string; status:string; district:string; title:string; description:string; date:string; detectedAt:string; source:string; target:string; affectedSystems:string[]; indicators:{ips:string[];domains:string[];hashes:string[]}; attackVector:string; impact:string; remediation:string; assignedTo:string; timeline:{date:string;event:string}[]; evidence:string[] }
export interface IpIntelligenceDTO { ip:string; reputation:string; reputationScore:number; geolocation:{city:string;region:string;country:string;lat:number;lng:number}; network:{isp:string;asn:string;org:string;type:string}; threatData:{riskLevel:number;incidentCount:number;firstSeen:string;lastSeen:string;categories:string[]}; associatedIncidents:{id:string;type:string;target:string}[] }
export interface DomainIntelligenceDTO { domain:string; threatScore:number; riskLevel:string; whois:{registrar:string;creationDate:string;expirationDate:string;organization:string;country:string}; ssl:{valid:boolean;issuer:string|null;expiryDate:string|null}; dns:{aRecords:string[];mxRecords:string[];nsRecords:string[]}; phishingProbability:number; categories:string[]; associatedIncidents:{id:string;type:string}[] }
export interface EvidenceRecordDTO { id:string; type:string; title:string; description:string; caseId:string; collectedAt:string; collectedBy:string; status:string; chainOfCustody:{action:string;by:string;at:string}[]; hash:string }
export interface NetworkFlowDTO { id:string; timestamp:string; sourceIp:string; destIp:string; sourcePort:number; destPort:number; protocol:string; bytes:number; packets:number; duration:number; threatIndicator:boolean; threatType:string }

function rec(raw: unknown): Record<string, unknown> { return raw && typeof raw === 'object' ? raw as Record<string, unknown> : {}; }
function str(v: unknown, f='Unknown') { return typeof v === 'string' && v.length ? v : f; }
function num(v: unknown, f=0) { return typeof v === 'number' && Number.isFinite(v) ? v : f; }
function bool(v: unknown) { return typeof v === 'boolean' ? v : false; }
function arr(v: unknown): string[] { return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : []; }
function timeline(v: unknown) { return Array.isArray(v) ? v.map((x)=>{const r=rec(x); return {date:str(r.date,''), event:str(r.event,'Update')};}) : []; }
function assocTarget(v: unknown) { return Array.isArray(v) ? v.map((x)=>{const r=rec(x); return {id:str(r.id,''), type:str(r.type,''), target:str(r.target,'')};}) : []; }
function assocDomain(v: unknown) { return Array.isArray(v) ? v.map((x)=>{const r=rec(x); return {id:str(r.id,''), type:str(r.type,'')};}) : []; }

export function adaptCyberIncident(raw: unknown): CyberIncidentDTO { const r=rec(raw); const ind=rec(r.indicators); return {id:str(r.id,'UNKNOWN-CYB'), type:str(r.type), severity:str(r.severity,'low'), status:str(r.status,'Open'), district:str(r.district), title:str(r.title), description:str(r.description), date:str(r.date,''), detectedAt:str(r.detectedAt,''), source:str(r.source), target:str(r.target), affectedSystems:arr(r.affectedSystems), indicators:{ips:arr(ind.ips), domains:arr(ind.domains), hashes:arr(ind.hashes)}, attackVector:str(r.attackVector), impact:str(r.impact), remediation:str(r.remediation), assignedTo:str(r.assignedTo), timeline:timeline(r.timeline), evidence:arr(r.evidence)}; }
export function adaptIpIntelligence(raw: unknown): IpIntelligenceDTO { const r=rec(raw), g=rec(r.geolocation), n=rec(r.network), t=rec(r.threatData); return {ip:str(r.ip,''), reputation:str(r.reputation,'low'), reputationScore:num(r.reputationScore), geolocation:{city:str(g.city),region:str(g.region),country:str(g.country),lat:num(g.lat),lng:num(g.lng)}, network:{isp:str(n.isp),asn:str(n.asn),org:str(n.org),type:str(n.type)}, threatData:{riskLevel:num(t.riskLevel),incidentCount:num(t.incidentCount),firstSeen:str(t.firstSeen,''),lastSeen:str(t.lastSeen,''),categories:arr(t.categories)}, associatedIncidents:assocTarget(r.associatedIncidents)}; }
export function adaptDomainIntelligence(raw: unknown): DomainIntelligenceDTO { const r=rec(raw), w=rec(r.whois), s=rec(r.ssl), d=rec(r.dns); return {domain:str(r.domain,''), threatScore:num(r.threatScore), riskLevel:str(r.riskLevel,'low'), whois:{registrar:str(w.registrar),creationDate:str(w.creationDate,''),expirationDate:str(w.expirationDate,''),organization:str(w.organization),country:str(w.country)}, ssl:{valid:bool(s.valid), issuer:typeof s.issuer==='string'?s.issuer:null, expiryDate:typeof s.expiryDate==='string'?s.expiryDate:null}, dns:{aRecords:arr(d.aRecords),mxRecords:arr(d.mxRecords),nsRecords:arr(d.nsRecords)}, phishingProbability:num(r.phishingProbability), categories:arr(r.categories), associatedIncidents:assocDomain(r.associatedIncidents)}; }
export function adaptEvidenceRecord(raw: unknown): EvidenceRecordDTO { const r=rec(raw); return {id:str(r.id), type:str(r.type), title:str(r.title), description:str(r.description), caseId:str(r.caseId), collectedAt:str(r.collectedAt,''), collectedBy:str(r.collectedBy), status:str(r.status), chainOfCustody:Array.isArray(r.chainOfCustody)?r.chainOfCustody.map((x)=>{const c=rec(x); return {action:str(c.action),by:str(c.by),at:str(c.at,'')};}):[], hash:str(r.hash,'')}; }
export function adaptNetworkFlow(raw: unknown): NetworkFlowDTO { const r=rec(raw); return {id:str(r.id), timestamp:str(r.timestamp,''), sourceIp:str(r.sourceIp,''), destIp:str(r.destIp,''), sourcePort:num(r.sourcePort), destPort:num(r.destPort), protocol:str(r.protocol), bytes:num(r.bytes), packets:num(r.packets), duration:num(r.duration), threatIndicator:bool(r.threatIndicator), threatType:str(r.threatType,'None')}; }
export function adaptCyberDto<T>(dto: T): T { return dto; }
