import { useMemo, useState } from 'react';
import { CorrelationGraph } from '@/features/network/components/CorrelationGraph';
import { CrimeNetworkGraph } from '@/features/network/components/CrimeNetworkGraph';
import { CyberNetworkGraph } from '@/features/network/components/CyberNetworkGraph';
import { GraphControls } from '@/features/network/components/GraphControls';
import { NodeDetailDrawer } from '@/features/network/components/NodeDetailDrawer';
import { useCorrelationGraph } from '@/features/network/hooks/useCorrelationGraph';
import { useCrimeNetwork } from '@/features/network/hooks/useCrimeNetwork';
import { useCyberNetwork } from '@/features/network/hooks/useCyberNetwork';
import type { GraphData, GraphElement } from '@/shared/api/dto-adapters/network';
import { EmptyState, ErrorState, LoadingSkeleton, PageHeader } from '@/shared/components';
import { Button } from '@/shared/ui-kit';

type Mode = 'crime' | 'cyber' | 'correlation';
function filterGraph(data: GraphData | undefined, query: string, types: string[]): GraphData | undefined { if(!data) return undefined; const q=query.toLowerCase(); const nodes=data.elements.nodes.filter(n=>(!q||String(n.data.label??n.data.id).toLowerCase().includes(q))&&(!types.length||types.includes(String(n.data.type)))); const ids=new Set(nodes.map(n=>n.data.id)); const edges=data.elements.edges.filter(e=>ids.has(String(e.data.source))&&ids.has(String(e.data.target))); return {elements:{nodes,edges}}; }

export default function NetworkOverviewPage(){ const [mode,setMode]=useState<Mode>('crime'); const [layout,setLayout]=useState('cose'); const [query,setQuery]=useState(''); const [types,setTypes]=useState<string[]>([]); const [selected,setSelected]=useState<GraphElement|null>(null); const crime=useCrimeNetwork(); const cyber=useCyberNetwork(); const corr=useCorrelationGraph(); const active=mode==='crime'?crime:mode==='cyber'?cyber:corr; const available=useMemo(()=>[...new Set((active.data?.elements.nodes??[]).map(n=>String(n.data.type)))],[active.data]); const graph=filterGraph(active.data,query,types.length?types:available); const nodeById=(id:string)=>setSelected(active.data?.elements.nodes.find(n=>n.data.id===id)??null); return <div className="grid gap-6"><PageHeader title="Network & Link Analysis" subtitle="Crime, cyber, and cross-domain relationship graph workspace."/><div className="flex flex-wrap gap-2"><Button variant={mode==='crime'?'primary':'secondary'} onClick={()=>setMode('crime')}>Crime Network</Button><Button variant={mode==='cyber'?'primary':'secondary'} onClick={()=>setMode('cyber')}>Cyber Network</Button><Button variant={mode==='correlation'?'primary':'secondary'} onClick={()=>setMode('correlation')}>Correlation Graph</Button></div><GraphControls onSearch={setQuery} onLayoutChange={setLayout} onFilterChange={setTypes} availableTypes={available}/>{active.isLoading?<LoadingSkeleton className="h-[70vh]" variant="chart"/>:null}{active.isError?<ErrorState message={active.error.message} onRetry={()=>void active.refetch()}/>:null}{!active.isLoading&&!active.isError&&(!graph||graph.elements.nodes.length===0)?<EmptyState title="No network data available" description="No graph nodes match the current controls."/>:null}{graph&&graph.elements.nodes.length>0?<section className="glass-card h-[70vh] overflow-hidden rounded-[var(--radius-2xl)] bg-[var(--color-background)]/70 p-2">{mode==='crime'?<CrimeNetworkGraph data={graph} layout={layout} onNodeClick={nodeById}/>:mode==='cyber'?<CyberNetworkGraph data={graph} layout={layout} onNodeClick={nodeById}/>:<CorrelationGraph data={graph} layout={layout} onNodeClick={nodeById}/>}</section>:null}<NodeDetailDrawer open={!!selected} node={selected} onClose={()=>setSelected(null)}/></div> }
